#!/bin/sh

set -e

echo "🚀 Running pre-push hook 🚀"

echo -e "\n🔧 Running tests..."

cd app-api
dotnet test
cd ..

echo -e "\n🔧 Installing/updating app on this computer..."

./install.sh

echo -e "\n🎉 Pre-push status: success 🎉\n"
