target-version = "py312"
line-length = 120

extend-exclude = [".ruff_cache", "__pycache__"]

[lint]
select = ["E", "F", "I", "UP", "B", "C4", "SIM", "ANN", "N", "TCH"]

[format]
quote-style = "single"
